# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    services:
      transactionserver:
        image: dafrito/transaction-server:2452637ac577dec1d2f0b51250ce436ffd520f54
        ports:
        - 8000:8000
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14]
    container: node:${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - run: npm ci
    - run: ping transactionserver || true
    - run: make
    - run: |
        mkdir parsegraph-transaction
        cp -r -t parsegraph-transaction package.json package-lock.json README.md demo/ LICENSE dist/
        tar cvzf parsegraph-transaction.tar.gz parsegraph-transaction/
    - uses: actions/upload-artifact@v2
      with:
        name: parsegraph-transaction-${{ github.run_number }}
        path: parsegraph-transaction.tar.gz
